version : '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    expose:
      - 2181
    networks:
      - shop
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - shop
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: Parola2510$
      POSTGRES_USER: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    networks:
      - shop
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672" #Management Port - default user:pass = guest:guest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - shop
  flower-shop:
    image: sha256:d1d3a44748cb940a5e62bdebcbe32257c2ee699ce218e1d83ddd53cc8e21906a
    #build:
    #  context: ./flower-shop/src/main/docker
     # dockerfile: Dockerfile.jvm
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Parola2510$
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - shop
    depends_on:
      - rabbitmq
      - postgres
      - kafka
  flower-customer:
    image: sha256:06e5d95af29bfc90579bad473b7d215fdd19bb6c883a9eb5b2a1f0f8610f48a8
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Parola2510$
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      FLOWERSHOP_URL: http://0.0.0.0:8080
      FLOWERDETAILS_URL: http://0.0.0.0:8082
    networks:
      - shop
    depends_on:
      - rabbitmq
      - postgres
      - kafka
  flower-details:
    image: sha256:494de8242312b44c3159165023858c8f8bd59383d61119a0a650d435fd85809e
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/shop
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Parola2510$
    networks:
      - shop
    depends_on:
      - postgres

networks:
  shop:
    driver: bridge